import {
  Flight,
  OperationalEvent,
  BaggageData,
  PassengerData,
  GroundServicesData,
  IncidentRecord,
  User,
} from '../types';

export const DEMO_USERS: User[] = [
  {
    id: 'usr_ramp_01',
    name: 'Tariq Al-Mansoor',
    badgeNumber: 'DOH-8821',
    role: 'ground_agent',
    department: 'Ramp Operations',
    email: 'tariq.mansoor@groundops.aero',
    avatar: 'TM',
  },
  {
    id: 'usr_sup_02',
    name: 'Sarah Jenkins',
    badgeNumber: 'DOH-1044',
    role: 'supervisor',
    department: 'Turnaround Control',
    email: 'sarah.jenkins@groundops.aero',
    avatar: 'SJ',
  },
  {
    id: 'usr_mgr_03',
    name: 'Capt. Faisal Qasim',
    badgeNumber: 'DOH-0019',
    role: 'ops_manager',
    department: 'Integrated Ops Center (IOC)',
    email: 'faisal.qasim@groundops.aero',
    avatar: 'FQ',
  },
  {
    id: 'usr_bag_04',
    name: 'Hassan Mahmoud',
    badgeNumber: 'DOH-5512',
    role: 'baggage_agent',
    department: 'Baggage Handling System',
    email: 'hassan.m@groundops.aero',
    avatar: 'HM',
  },
  {
    id: 'usr_maint_05',
    name: 'Elena Rostova',
    badgeNumber: 'DOH-7731',
    role: 'maintenance',
    department: 'Line Maintenance',
    email: 'elena.rostova@groundops.aero',
    avatar: 'ER',
  },
  {
    id: 'usr_adm_00',
    name: 'System Admin',
    badgeNumber: 'ADM-0001',
    role: 'admin',
    department: 'AeroTurn Administration',
    email: 'admin@groundops.aero',
    avatar: 'SA',
  },
];

// Helper to construct realistic ISO timestamps around current time
const now = new Date();
const getOffsetTimeIso = (minutesOffset: number): string => {
  const d = new Date(now.getTime() + minutesOffset * 60000);
  return d.toISOString();
};

export const INITIAL_FLIGHTS: Flight[] = [
  {
    id: 'flt_qr123',
    flightNumber: 'QR123',
    callsign: 'QTR123',
    airline: 'Qatar Airways',
    airlineCode: 'QR',
    originIata: 'DOH',
    originAirport: 'Hamad International',
    destinationIata: 'LHR',
    destinationAirport: 'London Heathrow',
    aircraftType: 'A350-1000',
    aircraftReg: 'A7-ANE',
    gate: 'C12',
    terminal: 'Terminal 1',
    stand: 'Ramp 42',
    status: 'TURNAROUND',
    scheduledArrival: getOffsetTimeIso(-50),
    actualArrival: getOffsetTimeIso(-45),
    scheduledDeparture: getOffsetTimeIso(40),
    estimatedDeparture: getOffsetTimeIso(52),
    targetTurnaroundMin: 90,
    actualTurnaroundMin: 97,
    delayMinutes: 12,
    totalPassengers: 287,
    boardedPassengers: 142,
    totalBaggage: 241,
    loadedBaggage: 180,
    unloadedBaggage: 241,
    assignedSupervisor: 'Sarah Jenkins',
    assignedAgent: 'Tariq Al-Mansoor',
    openIncidentsCount: 1,
    createdAt: getOffsetTimeIso(-120),
    updatedAt: getOffsetTimeIso(-2),
    delayReasons: [
      {
        id: 'del_qr123_1',
        flightId: 'flt_qr123',
        iataCode: '81',
        category: 'Passenger & Baggage',
        description: 'Late connecting transit passenger reconciliation from QR832',
        delayMinutes: 12,
        isPrimary: true,
        reportedBy: 'Sarah Jenkins',
        createdAt: getOffsetTimeIso(-10),
      },
    ],
  },
  {
    id: 'flt_ek201',
    flightNumber: 'EK201',
    callsign: 'UAE201',
    airline: 'Emirates',
    airlineCode: 'EK',
    originIata: 'DXB',
    originAirport: 'Dubai International',
    destinationIata: 'JFK',
    destinationAirport: 'New York JFK',
    aircraftType: 'A380-800',
    aircraftReg: 'A6-EVS',
    gate: 'A4',
    terminal: 'Terminal 1',
    stand: 'Stand A4',
    status: 'BOARDING',
    scheduledArrival: getOffsetTimeIso(-85),
    actualArrival: getOffsetTimeIso(-82),
    scheduledDeparture: getOffsetTimeIso(15),
    estimatedDeparture: getOffsetTimeIso(15),
    targetTurnaroundMin: 100,
    delayMinutes: 0,
    totalPassengers: 489,
    boardedPassengers: 412,
    totalBaggage: 512,
    loadedBaggage: 512,
    unloadedBaggage: 512,
    assignedSupervisor: 'Sarah Jenkins',
    assignedAgent: 'Tariq Al-Mansoor',
    openIncidentsCount: 0,
    createdAt: getOffsetTimeIso(-180),
    updatedAt: getOffsetTimeIso(-1),
  },
  {
    id: 'flt_qr456',
    flightNumber: 'QR456',
    callsign: 'QTR456',
    airline: 'Qatar Airways',
    airlineCode: 'QR',
    originIata: 'DOH',
    originAirport: 'Hamad International',
    destinationIata: 'CDG',
    destinationAirport: 'Paris Charles de Gaulle',
    aircraftType: 'B777-300ER',
    aircraftReg: 'A7-BEV',
    gate: 'B8',
    terminal: 'Terminal 1',
    stand: 'Stand B8',
    status: 'ARRIVING',
    scheduledArrival: getOffsetTimeIso(10),
    estimatedArrival: getOffsetTimeIso(12),
    scheduledDeparture: getOffsetTimeIso(95),
    estimatedDeparture: getOffsetTimeIso(95),
    targetTurnaroundMin: 85,
    delayMinutes: 0,
    totalPassengers: 312,
    boardedPassengers: 0,
    totalBaggage: 330,
    loadedBaggage: 0,
    unloadedBaggage: 0,
    assignedSupervisor: 'Sarah Jenkins',
    assignedAgent: 'Tariq Al-Mansoor',
    openIncidentsCount: 0,
    createdAt: getOffsetTimeIso(-90),
    updatedAt: getOffsetTimeIso(-5),
  },
  {
    id: 'flt_ey101',
    flightNumber: 'EY101',
    callsign: 'ETD101',
    airline: 'Etihad Airways',
    airlineCode: 'EY',
    originIata: 'AUH',
    originAirport: 'Abu Dhabi Zayed Intl',
    destinationIata: 'FRA',
    destinationAirport: 'Frankfurt Main',
    aircraftType: 'B787-9',
    aircraftReg: 'A6-BLJ',
    gate: 'D2',
    terminal: 'Terminal 1',
    stand: 'Stand D2',
    status: 'READY',
    scheduledArrival: getOffsetTimeIso(-110),
    actualArrival: getOffsetTimeIso(-115),
    scheduledDeparture: getOffsetTimeIso(5),
    estimatedDeparture: getOffsetTimeIso(5),
    targetTurnaroundMin: 75,
    delayMinutes: 0,
    totalPassengers: 231,
    boardedPassengers: 231,
    totalBaggage: 210,
    loadedBaggage: 210,
    unloadedBaggage: 210,
    assignedSupervisor: 'Sarah Jenkins',
    assignedAgent: 'Hassan Mahmoud',
    openIncidentsCount: 0,
    createdAt: getOffsetTimeIso(-200),
    updatedAt: getOffsetTimeIso(-3),
  },
  {
    id: 'flt_ba117',
    flightNumber: 'BA117',
    callsign: 'BAW117',
    airline: 'British Airways',
    airlineCode: 'BA',
    originIata: 'LHR',
    originAirport: 'London Heathrow',
    destinationIata: 'DOH',
    destinationAirport: 'Hamad International',
    aircraftType: 'A350-1000',
    aircraftReg: 'G-XWBA',
    gate: 'C14',
    terminal: 'Terminal 1',
    stand: 'Stand C14',
    status: 'DEPARTED',
    scheduledArrival: getOffsetTimeIso(-180),
    actualArrival: getOffsetTimeIso(-175),
    scheduledDeparture: getOffsetTimeIso(-60),
    estimatedDeparture: getOffsetTimeIso(-58),
    actualDeparture: getOffsetTimeIso(-58),
    targetTurnaroundMin: 90,
    delayMinutes: 0,
    totalPassengers: 294,
    boardedPassengers: 294,
    totalBaggage: 280,
    loadedBaggage: 280,
    unloadedBaggage: 280,
    assignedSupervisor: 'Sarah Jenkins',
    assignedAgent: 'Tariq Al-Mansoor',
    openIncidentsCount: 0,
    createdAt: getOffsetTimeIso(-240),
    updatedAt: getOffsetTimeIso(-55),
  },
  {
    id: 'flt_aa100',
    flightNumber: 'AA100',
    callsign: 'AAL100',
    airline: 'American Airlines',
    airlineCode: 'AA',
    originIata: 'JFK',
    originAirport: 'New York JFK',
    destinationIata: 'LHR',
    destinationAirport: 'London Heathrow',
    aircraftType: 'B777-200ER',
    aircraftReg: 'N780AN',
    gate: 'E1',
    terminal: 'Terminal 1',
    stand: 'Ramp 18',
    status: 'DELAYED',
    scheduledArrival: getOffsetTimeIso(-90),
    actualArrival: getOffsetTimeIso(-60),
    scheduledDeparture: getOffsetTimeIso(-10),
    estimatedDeparture: getOffsetTimeIso(35),
    targetTurnaroundMin: 80,
    delayMinutes: 45,
    totalPassengers: 273,
    boardedPassengers: 88,
    totalBaggage: 260,
    loadedBaggage: 120,
    unloadedBaggage: 260,
    assignedSupervisor: 'Sarah Jenkins',
    assignedAgent: 'Tariq Al-Mansoor',
    openIncidentsCount: 1,
    createdAt: getOffsetTimeIso(-150),
    updatedAt: getOffsetTimeIso(-4),
    delayReasons: [
      {
        id: 'del_aa100_1',
        flightId: 'flt_aa100',
        iataCode: '41',
        category: 'Aircraft Defect / Technical',
        description: 'APU bleed valve pressure sensor inspection & replacement',
        delayMinutes: 45,
        isPrimary: true,
        reportedBy: 'Elena Rostova',
        createdAt: getOffsetTimeIso(-30),
      },
    ],
  },
];

export const INITIAL_EVENTS: OperationalEvent[] = [
  // QR123 Timeline events
  {
    id: 'evt_qr123_01',
    flightId: 'flt_qr123',
    eventType: 'LANDING',
    eventTitle: 'Aircraft Touchdown (Touchdown)',
    category: 'ARRIVAL',
    status: 'COMPLETED',
    eventTimeUtc: getOffsetTimeIso(-48),
    deviceTime: getOffsetTimeIso(-48),
    serverReceivedTime: getOffsetTimeIso(-47),
    syncTime: getOffsetTimeIso(-47),
    airportTimezone: 'Asia/Qatar',
    userId: 'usr_sup_02',
    userName: 'Sarah Jenkins',
    userRole: 'supervisor',
    deviceId: 'iPad-DOH-T1-04',
    syncStatus: 'SYNCED',
    notes: 'Runway 34R touchdown, taxiing to Gate C12.',
    gps: {
      latitude: 25.2635,
      longitude: 51.6142,
      accuracy: 6,
      timestamp: Date.now() - 48 * 60000,
      status: 'HIGH_ACCURACY',
    },
    createdAt: getOffsetTimeIso(-48),
    updatedAt: getOffsetTimeIso(-48),
  },
  {
    id: 'evt_qr123_02',
    flightId: 'flt_qr123',
    eventType: 'ON_BLOCK',
    eventTitle: 'Aircraft On Block (AIBT)',
    category: 'ARRIVAL',
    status: 'COMPLETED',
    eventTimeUtc: getOffsetTimeIso(-45),
    deviceTime: getOffsetTimeIso(-45),
    serverReceivedTime: getOffsetTimeIso(-44),
    syncTime: getOffsetTimeIso(-44),
    airportTimezone: 'Asia/Qatar',
    userId: 'usr_ramp_01',
    userName: 'Tariq Al-Mansoor',
    userRole: 'ground_agent',
    deviceId: 'RuggedTab-DOH-88',
    syncStatus: 'SYNCED',
    notes: 'Parked at Gate C12. Marshalled with VDGS.',
    gate: 'C12',
    stand: 'Ramp 42',
    gps: {
      latitude: 25.2635,
      longitude: 51.6142,
      accuracy: 5,
      timestamp: Date.now() - 45 * 60000,
      status: 'HIGH_ACCURACY',
    },
    createdAt: getOffsetTimeIso(-45),
    updatedAt: getOffsetTimeIso(-45),
  },
  {
    id: 'evt_qr123_03',
    flightId: 'flt_qr123',
    eventType: 'CHOCKS_ON',
    eventTitle: 'Wheel Chocks Placed & GPU Connected',
    category: 'ARRIVAL',
    status: 'COMPLETED',
    eventTimeUtc: getOffsetTimeIso(-44),
    deviceTime: getOffsetTimeIso(-44),
    serverReceivedTime: getOffsetTimeIso(-43),
    syncTime: getOffsetTimeIso(-43),
    airportTimezone: 'Asia/Qatar',
    userId: 'usr_ramp_01',
    userName: 'Tariq Al-Mansoor',
    userRole: 'ground_agent',
    deviceId: 'RuggedTab-DOH-88',
    syncStatus: 'SYNCED',
    notes: 'Main gear chocks secured. Ground Power Unit 115V 400Hz connected.',
    gps: {
      latitude: 25.2635,
      longitude: 51.6142,
      accuracy: 5,
      timestamp: Date.now() - 44 * 60000,
      status: 'HIGH_ACCURACY',
    },
    createdAt: getOffsetTimeIso(-44),
    updatedAt: getOffsetTimeIso(-44),
  },
  {
    id: 'evt_qr123_04',
    flightId: 'flt_qr123',
    eventType: 'DOOR_OPEN',
    eventTitle: 'Aircraft Door 1L Open & Jet Bridge Attached',
    category: 'ARRIVAL',
    status: 'COMPLETED',
    eventTimeUtc: getOffsetTimeIso(-42),
    deviceTime: getOffsetTimeIso(-42),
    serverReceivedTime: getOffsetTimeIso(-41),
    syncTime: getOffsetTimeIso(-41),
    airportTimezone: 'Asia/Qatar',
    userId: 'usr_ramp_01',
    userName: 'Tariq Al-Mansoor',
    userRole: 'ground_agent',
    deviceId: 'RuggedTab-DOH-88',
    syncStatus: 'SYNCED',
    notes: 'Passenger boarding bridge docked safely.',
    createdAt: getOffsetTimeIso(-42),
    updatedAt: getOffsetTimeIso(-42),
  },
  {
    id: 'evt_qr123_05',
    flightId: 'flt_qr123',
    eventType: 'BAGGAGE_UNLOAD_STARTED',
    eventTitle: 'Inbound Baggage Unloading Started',
    category: 'GROUND_SERVICES',
    status: 'COMPLETED',
    eventTimeUtc: getOffsetTimeIso(-40),
    deviceTime: getOffsetTimeIso(-40),
    serverReceivedTime: getOffsetTimeIso(-39),
    syncTime: getOffsetTimeIso(-39),
    airportTimezone: 'Asia/Qatar',
    userId: 'usr_bag_04',
    userName: 'Hassan Mahmoud',
    userRole: 'baggage_agent',
    deviceId: 'Handheld-BHS-12',
    syncStatus: 'SYNCED',
    notes: 'Belt loader 4A engaged at aft cargo hold.',
    createdAt: getOffsetTimeIso(-40),
    updatedAt: getOffsetTimeIso(-40),
  },
  {
    id: 'evt_qr123_06',
    flightId: 'flt_qr123',
    eventType: 'DISEMBARK_COMPLETED',
    eventTitle: 'Passenger Disembarkation Completed',
    category: 'ARRIVAL',
    status: 'COMPLETED',
    eventTimeUtc: getOffsetTimeIso(-30),
    deviceTime: getOffsetTimeIso(-30),
    serverReceivedTime: getOffsetTimeIso(-29),
    syncTime: getOffsetTimeIso(-29),
    airportTimezone: 'Asia/Qatar',
    userId: 'usr_ramp_01',
    userName: 'Tariq Al-Mansoor',
    userRole: 'ground_agent',
    deviceId: 'RuggedTab-DOH-88',
    syncStatus: 'SYNCED',
    notes: 'Cabin all clear of inbound passengers.',
    createdAt: getOffsetTimeIso(-30),
    updatedAt: getOffsetTimeIso(-30),
  },
  {
    id: 'evt_qr123_07',
    flightId: 'flt_qr123',
    eventType: 'CLEANING_STARTED',
    eventTitle: 'Cabin Deep Cleaning Started',
    category: 'GROUND_SERVICES',
    status: 'COMPLETED',
    eventTimeUtc: getOffsetTimeIso(-28),
    deviceTime: getOffsetTimeIso(-28),
    serverReceivedTime: getOffsetTimeIso(-27),
    syncTime: getOffsetTimeIso(-27),
    airportTimezone: 'Asia/Qatar',
    userId: 'usr_ramp_01',
    userName: 'Tariq Al-Mansoor',
    userRole: 'ground_agent',
    deviceId: 'RuggedTab-DOH-88',
    syncStatus: 'SYNCED',
    notes: '12 cleaners boarded.',
    createdAt: getOffsetTimeIso(-28),
    updatedAt: getOffsetTimeIso(-28),
  },
  {
    id: 'evt_qr123_08',
    flightId: 'flt_qr123',
    eventType: 'CATERING_STARTED',
    eventTitle: 'Catering Hi-Lift Docked & Loading Started',
    category: 'GROUND_SERVICES',
    status: 'COMPLETED',
    eventTimeUtc: getOffsetTimeIso(-25),
    deviceTime: getOffsetTimeIso(-25),
    serverReceivedTime: getOffsetTimeIso(-24),
    syncTime: getOffsetTimeIso(-24),
    airportTimezone: 'Asia/Qatar',
    userId: 'usr_ramp_01',
    userName: 'Tariq Al-Mansoor',
    userRole: 'ground_agent',
    deviceId: 'RuggedTab-DOH-88',
    syncStatus: 'SYNCED',
    notes: 'QACC catering truck docked Door 2R & 4R.',
    createdAt: getOffsetTimeIso(-25),
    updatedAt: getOffsetTimeIso(-25),
  },
  {
    id: 'evt_qr123_09',
    flightId: 'flt_qr123',
    eventType: 'FUEL_STARTED',
    eventTitle: 'Aircraft Refueling Started',
    category: 'GROUND_SERVICES',
    status: 'IN_PROGRESS',
    eventTimeUtc: getOffsetTimeIso(-20),
    deviceTime: getOffsetTimeIso(-20),
    serverReceivedTime: getOffsetTimeIso(-19),
    syncTime: getOffsetTimeIso(-19),
    airportTimezone: 'Asia/Qatar',
    userId: 'usr_ramp_01',
    userName: 'Tariq Al-Mansoor',
    userRole: 'ground_agent',
    deviceId: 'RuggedTab-DOH-88',
    syncStatus: 'SYNCED',
    notes: 'Target uplift: 68,000 kg Jet A-1. Hydrant dispenser engaged.',
    createdAt: getOffsetTimeIso(-20),
    updatedAt: getOffsetTimeIso(-20),
  },
  {
    id: 'evt_qr123_10',
    flightId: 'flt_qr123',
    eventType: 'BOARDING_STARTED',
    eventTitle: 'Outbound Passenger Boarding Started',
    category: 'DEPARTURE',
    status: 'IN_PROGRESS',
    eventTimeUtc: getOffsetTimeIso(-10),
    deviceTime: getOffsetTimeIso(-10),
    serverReceivedTime: getOffsetTimeIso(-9),
    syncTime: getOffsetTimeIso(-9),
    airportTimezone: 'Asia/Qatar',
    userId: 'usr_sup_02',
    userName: 'Sarah Jenkins',
    userRole: 'supervisor',
    deviceId: 'iPad-DOH-T1-04',
    syncStatus: 'SYNCED',
    notes: 'Priority & Special Assistance boarding in progress. 142/287 boarded.',
    createdAt: getOffsetTimeIso(-10),
    updatedAt: getOffsetTimeIso(-10),
  },
  {
    id: 'evt_qr123_11',
    flightId: 'flt_qr123',
    eventType: 'DOORS_CLOSED',
    eventTitle: 'Aircraft Doors Closed & Slides Armed',
    category: 'DEPARTURE',
    status: 'PENDING',
    eventTimeUtc: getOffsetTimeIso(30),
    deviceTime: getOffsetTimeIso(30),
    airportTimezone: 'Asia/Qatar',
    userId: 'usr_ramp_01',
    userName: 'Tariq Al-Mansoor',
    userRole: 'ground_agent',
    deviceId: 'RuggedTab-DOH-88',
    syncStatus: 'PENDING',
    notes: 'Scheduled for T-10m before pushback.',
    createdAt: getOffsetTimeIso(-120),
    updatedAt: getOffsetTimeIso(-120),
  },
  {
    id: 'evt_qr123_12',
    flightId: 'flt_qr123',
    eventType: 'PUSHBACK',
    eventTitle: 'Tug Connected & Pushback Authorized',
    category: 'DEPARTURE',
    status: 'PENDING',
    eventTimeUtc: getOffsetTimeIso(40),
    deviceTime: getOffsetTimeIso(40),
    airportTimezone: 'Asia/Qatar',
    userId: 'usr_ramp_01',
    userName: 'Tariq Al-Mansoor',
    userRole: 'ground_agent',
    deviceId: 'RuggedTab-DOH-88',
    syncStatus: 'PENDING',
    notes: 'Ground tow tug standby.',
    createdAt: getOffsetTimeIso(-120),
    updatedAt: getOffsetTimeIso(-120),
  },
];

export const INITIAL_BAGGAGE: Record<string, BaggageData> = {
  flt_qr123: {
    id: 'bag_qr123',
    flightId: 'flt_qr123',
    totalBags: 241,
    loadedBags: 180,
    unloadedBags: 241,
    missingBags: 1,
    damagedBags: 2,
    lateBags: 4,
    specialBags: 14,
    transferBags: 68,
    containerUldList: ['AKE10294QR', 'AKE44921QR', 'AKE98122QR', 'AKE33019QR'],
    damageReportNotes: 'Two hard-shell Samsonite bags suffered scuffed outer handles during transit offload.',
    status: 'IN_PROGRESS',
    updatedAt: getOffsetTimeIso(-10),
  },
};

export const INITIAL_PASSENGERS: Record<string, PassengerData> = {
  flt_qr123: {
    id: 'pax_qr123',
    flightId: 'flt_qr123',
    booked: 291,
    checkedIn: 287,
    boarded: 142,
    noShow: 4,
    transit: 165,
    specialAssistance: {
      wheelchair: 8,
      unaccompaniedMinor: 2,
      medical: 1,
      infants: 6,
      vip: 4,
    },
    boardingZones: {
      zone1: { name: 'First & Business / Priority', boarded: 42, total: 46, open: true },
      zone2: { name: 'Zone A (Rows 10-24)', boarded: 58, total: 80, open: true },
      zone3: { name: 'Zone B (Rows 25-40)', boarded: 32, total: 85, open: false },
      zone4: { name: 'Zone C (Rows 41-55)', boarded: 10, total: 80, open: false },
    },
    reconciliationStatus: 'IN_PROGRESS',
    gateStatus: 'OPEN',
    updatedAt: getOffsetTimeIso(-8),
  },
};

export const INITIAL_GROUND_SERVICES: Record<string, GroundServicesData> = {
  flt_qr123: {
    id: 'srv_qr123',
    flightId: 'flt_qr123',
    cleaning: {
      startedAt: getOffsetTimeIso(-28),
      completedAt: getOffsetTimeIso(-12),
      crewCount: 12,
      cleaningType: 'TRANSIT_QUICK',
      inspectedBy: 'Tariq Al-Mansoor',
      inspectionPassed: true,
      status: 'COMPLETED',
      problemNotes: 'Lavatory forward 1 required sanitization spray refresh.',
    },
    catering: {
      startedAt: getOffsetTimeIso(-25),
      completedAt: getOffsetTimeIso(-8),
      truckCount: 2,
      mealsLoaded: 287,
      specialMealsCount: 38,
      barCartsLoaded: 16,
      securitySealNumbers: ['QACC-88192A', 'QACC-88192B', 'QACC-88193C'],
      supplierName: 'Qatar Aviation Catering Company (QACC)',
      status: 'COMPLETED',
      notes: 'All 38 special dietary meals verified and matched to passenger manifest.',
    },
    fueling: {
      startedAt: getOffsetTimeIso(-20),
      plannedFuelKg: 68000,
      actualFuelKg: 52000,
      fuelDensity: 0.804,
      truckId: 'HYD-DOH-24',
      supplier: 'WOQOD Aviation Fueling',
      safetyBondingConfirmed: true,
      waterCheckPassed: true,
      meterBeforeLiters: 1420800,
      meterAfterLiters: 1485500,
      status: 'IN_PROGRESS',
      notes: 'Pumping rate: 1,800 L/min. Safe clearance maintained around wings.',
    },
    maintenance: {
      required: false,
      releaseToService: true,
      technicianName: 'Elena Rostova',
      technicianLicense: 'EASA-B1-99214',
      status: 'COMPLETED',
      notes: 'Transit visual walk-around inspection complete. Tire pressures, brake wear pins, engine fan blades in green limits.',
    },
    cargo: {
      cargoWeightKg: 14200,
      mailWeightKg: 850,
      uldLoadedCount: 12,
      uldUnloadedCount: 14,
      dgrNotocSigned: true,
      liveAnimalsOnBoard: false,
      perishableCargo: true,
      status: 'IN_PROGRESS',
      notes: 'NOTOC (Notification to Captain) prepared for 2 lithium battery consignments.',
    },
    updatedAt: getOffsetTimeIso(-5),
  },
};

export const INITIAL_INCIDENTS: IncidentRecord[] = [
  {
    id: 'inc_01',
    flightId: 'flt_qr123',
    flightNumber: 'QR123',
    category: 'PASSENGER',
    severity: 'MEDIUM',
    title: 'Transit Passenger Connection Delay (QR832)',
    description: '4 high-tier business passengers inbound on delayed feeder QR832 from Bangkok requiring priority buggy escort to Gate C12.',
    location: 'Gate C12 / Transfer Security Central',
    gate: 'C12',
    reportedBy: 'Sarah Jenkins',
    reportedByUserId: 'usr_sup_02',
    assignedDepartment: 'Passenger Service / Special Handling',
    reportedAtUtc: getOffsetTimeIso(-15),
    status: 'INVESTIGATING',
    syncStatus: 'SYNCED',
    gps: {
      latitude: 25.2635,
      longitude: 51.6142,
      accuracy: 6,
      timestamp: Date.now() - 15 * 60000,
      status: 'HIGH_ACCURACY',
    },
  },
  {
    id: 'inc_02',
    flightId: 'flt_aa100',
    flightNumber: 'AA100',
    category: 'TECHNICAL',
    severity: 'HIGH',
    title: 'APU Bleed Air Pressure Fault',
    description: 'Cockpit crew reported erratic pressure sensor readouts from auxiliary power unit. Line maintenance technician dispatched.',
    location: 'Gate E1 (Ramp 18)',
    gate: 'E1',
    reportedBy: 'Elena Rostova',
    reportedByUserId: 'usr_maint_05',
    assignedDepartment: 'Line Maintenance',
    reportedAtUtc: getOffsetTimeIso(-35),
    status: 'ACTION_REQUIRED',
    syncStatus: 'SYNCED',
  },
];
